### ISSUE TITLE
Build issues on Windows using VS2015

### ISSUE THREAD

**Issue by 0xbc** [angr/pyvex#64]
Hi all,

I've been having a problem building `pyvex` on Windows 10 with Visual Studio 2015 (no Cygwin or MinGW). The issue is related to how `make_ffi.py` is invoking preprocessing tools (for more context on how I disovered it, see angr/angr-dev#16).

If I run `python setup.py develop` in the `pyvex` source tree from a VS2015 developer prompt, I get the following exception and stack trace:

```
Creating CFFI defs file
No handlers could be found for logger "cffier"
Exception('Couldn\'t process pyvex headers.Please set CPP environmental variable to local path of "cpp".Note that "cpp" and "g++" are different.',)
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    'pyvex': ['lib/*', 'include/*']
  File "c:\python27\Lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\python27\Lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\python27\Lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 112, in run
    self.execute(_build_ffi, (), msg="Creating CFFI defs file")
  File "c:\python27\Lib\distutils\cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "c:\python27\Lib\distutils\util.py", line 309, in execute
    func(*args)
  File "setup.py", line 90, in _build_ffi
    make_ffi.doit(os.path.join(VEX_PATH,'pub'))
  File "c:\src\pyvex\make_ffi.py", line 88, in doit
    "Note that \"cpp\" and \"g++\" are different."
Exception: Couldn't process pyvex headers.Please set CPP environmental variable to local path of "cpp".Note that "cpp" and "g++" are different.
```
Currently, `make_ffi.py` tries a whole bunch of preprocessors in a loop (starting at line [66](https://github.com/angr/pyvex/blob/fb0b164/make_ffi.py#L66)), the first of which is VS's `cl` with the relevant arguments appended. This should (and in fact does) work fine in terms of generating the correct output... however, the current heuristic for detecting failure (at line [75](https://github.com/angr/pyvex/blob/fb0b164/make_ffi.py#L75)) assumes that `stderr` will be `None` if no problems were encountered. This assumption doesn't hold for `cl`, as it prints a version string to `stderr` (whereas the rest of the output goes to `stdout`). 

An obvious fix for `cl` (and hence for VS2015 support) would be to remove the `or stderr` clause from the if statement at line 75, but I don't know if this would then break appropriate error detection for other tools like `cpp`, `clang` et al. If I get time later, I'll try and test the results with some of those other tools, but not sure when I'll get around to that. 

Any advice/comments/suggestions appreciated! If someone has authoritative guidance on what patch would be most appropriate for all the possible preprocessing tools, I'm happy to submit the relevant PR. 

cheers,
Ben

**Comment by rhelmot** [comment]
My initial thought is that removing the stderr check entirely should fix it. in fact it looks like the somewhat-related #58 will actually fix this. It looks like whatever issues were preventing that from being merged have cleared up, so I merged it. Can you try with the latest master?

**Comment by 0xbc** [comment]
Tested with the latest master - still the same problem with VS2015/cl (`stderr` is not `None` so the loop considers it to have failed and doesn't break out). Do you want a PR with `or stderr` gone?

**Comment by rhelmot** [comment]
That is really bizzare - I would have sworn the diff for that pr involved removing stderr. I've removed it myself, can you try it again?

**Comment by 0xbc** [comment]
Cool... yep, looks good to go now, thanks!
